### PR TITLE
Added compile tests for Video For Windows and GDI Plus instead of FindPackage cmake methods

### PR DESCRIPTION
**Pull request by ChrisSchulte**
As discussed in issue #55 here is a proposal of replacing the find package methods by two try compile checks for Video for Windows and for GDI Plus on Windows platforms. Tested agains Windows 10 with and without SDK 10.

### CODE REVIEW

**Comment by VolkerEnderlein** [comment]
Hi Chris, I checked the PR, simage can be compiled and built but I had a more minimal approach in mind, see attached CMakeLists.txt. Maybe you can check this out and adapt this PR if you think it fits better. Otherwise I am happy to merge your PR as is. Cheers Volker
[CMakeLists.txt](https://github.com/coin3d/simage/files/8429368/CMakeLists.txt)

**Comment by ChrisSchulte** [comment]
Hi Volker, I'm sorry but I can't see any differences between my CMakeLists.txt and the one you attached. Are you sure you attached the right file ?
Cheers, Chris

**Comment by VolkerEnderlein** [comment]
You ar right I mixed up the attachment. Please have a look at the new file here.
[CMakeLists.txt](https://github.com/coin3d/simage/files/8441058/CMakeLists.txt)

**Comment by ChrisSchulte** [comment]
Hi Volker,
I've checked your solution and it does work for me. It is clearly an easier solution but in my opinion it is better to externalize the tests as it makes the CmakeLists file easier to read and to evolve. Both solution work so it is up to you to choose which one you want to implement, as you are the maintainer. 
Cheers Chris

**Comment by VolkerEnderlein** [comment]
I finally decided to use the simplest solution as I do not expect much growing in simage's build system. Anyway, thanks a lot for your thorough issue report and the valuable contribution.

**Pull request closed without merging**
